rpc:
  enable: true
  port: :8080
  token: ""
  tls:
    enable: false
    cert_file: ""
    key_file: ""
debug: false
interval: 20
out_put_path: /srv/bililive
feature:
  use_native_flv_parser: false
live_rooms:
