rpc:
  enable: false
  port: 127.0.0.1:8080
  token: ""
  tls:
    enable: false
    cert_file: ""
    key_file: ""
debug: false
interval: 15
out_put_path: /Users/chigusa/Movies
feature:
  use_native_flv_parser: false
live_rooms: